name: Deploy Telegram Bot

on:
  push:
    branches:
      - bot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Telegram bot files
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass rsync

          mkdir -p /tmp/ssh
          ssh-keyscan -H $HOST >> /tmp/ssh/known_hosts

          RSYNC_SSH="sshpass -p '$PASSWORD' ssh -o UserKnownHostsFile=/tmp/ssh/known_hosts -o StrictHostKeyChecking=yes"
          sshpass -p "$PASSWORD" rsync -avz --delete -e "$RSYNC_SSH" ./ root@$HOST:/var/www/WbCashBackBot/